spring:
  application:
    name: rag
  profiles:
    active: dev
  ai:
    openai:
      api-key:
      chat:
        options:
          model: gpt-4o
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral:7b
    vectorstore:
      pgvector:
        table-name-for-chat-memory: vector_store
        table-name-for-rag: rag_advance_vector_store
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10_000
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: postgres

app:
  rag:
    force-rebuild: false
    top-k: 20 # 4
    similarity-threshold: 0.0
    radius: 1
    chunk:
      size: 100 # 800
      min-chunk-size: 200
      min-chunk-to-embed: 50
      max-chunk-size: 8192
      keep-separator: true
    pdf:
      mode: page
      path: file:/home/shamim/Code/My-Code/SpringAI/rag/src/main/resources/rag/qa-over-internal-docs/*.pdf
      pages-per-document: 1
      left-alignment: true
      number-of-top-text-line-to-delete: 0
      number-of-bottom-text-line-to-delete: 0
    query-expander:
      number-of-query: 4
    synonyms:
      PTO: "paid time off"
      SSO: "single sign-on"
      MFA: "multi-factor authentication"
      2FA: "two-factor authentication"
      IaC: "infrastructure as code"
      PII: "personal data"
      CI/CD: "continuous integration and delivery"
      NAT: "network address translation"
      GDPR: "data protection regulation"
      VPN: "virtual private network"
      SDLC: "software development lifecycle"
      DNS: "domain name system"
      IP: "internet protocol"
      API: "application programming interface"
      SDK: "software development kit"
      UI: "user interface"
      UX: "user experience"
      DB: "database"
      SQL: "structured query language"
      NoSQL: "non-relational database"
      OS: "operating system"
      SSH: "secure shell"
      HTTP: "hypertext transfer protocol"
      HTTPS: "secure hypertext transfer protocol"

logging:
  level:
    root: info
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug