server:
  port: 8088

spring:
  application:
    name: mcp-server
  ai:
    mcp:
      server:
        name: custom-mcp-server
        version: 1.0.0
        protocol: streamable
        streamable-http:
          mcp-endpoint: /mcp