spring:
  application:
    name: chat-memory-pg-vector
  profiles:

    # The `openai` will enable OpenAI config, and dev will override the API Key
    # dev must be at the end
#    active: openai, dev

    # The `docker-model-runner` will enable OpenAI config, and dev will override the API Key
    # dev must be at the end
    active: docker-model-runner, dev